name: CI for unique ogp growi

on:
  push:

  pull_request:
    types: [opened, closed]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: npm install
        working-directory: ./src
        run: |
          npm install

      - name: run jest
        working-directory: ./src
        run: |
          npm run test
